### ISSUE TITLE
Visualizations lightbox: intermittently does not work

### ISSUE THREAD

**Issue by ethompson-pellucid** [brettcrockett/brettcrockett.github.io#12]
Links from homepage and on product overview ("Take a closer look")

**Comment by ethompson-pellucid** [comment]
Images are in assets/images/sample-charts

**Comment by ethompson-pellucid** [comment]
Note: Lightbox should be accessible from three locations.

Homepage (2 links)
![screen shot 2016-08-11 at 10 35 19 am](https://cloud.githubusercontent.com/assets/5314280/17596585/624ef512-5faf-11e6-8007-18b431ea3bca.png)

Product overview (1 link)
![screen shot 2016-08-11 at 10 35 12 am](https://cloud.githubusercontent.com/assets/5314280/17596584/624b6514-5faf-11e6-9ca7-944758718f39.png)

**Comment by brettcrockett** [comment]
@ethompson-pellucid or @melinachastain -- the functionality should now be restored, were one of you better placed to stylize the image sizes / buttons / etc?

**Comment by ethompson-pellucid** [comment]
Did this stop working again?

**Comment by brettcrockett** [comment]
Works for me?


Brett

+1 720 336 5150  Direct
+1 720 278 5808  Cell

**Comment by ethompson-pellucid** [comment]
Ah, it's working on my local but not https://brettcrockett.github.io/

**Comment by brettcrockett** [comment]
It works for me everytime I do a hard refresh. Not cool Intermittent
issues...


Brett

+1 720 336 5150  Direct
+1 720 278 5808  Cell

**Comment by brettcrockett** [comment]
@joelpellucid Would you mind having a look at this? The lightbox intermittently does not work. For me, it works after a hard refresh (ctrl+f5). After a soft refresh (f5), it stops working. Seems odd?

**Comment by ethompson-pellucid** [comment]
I'm having the same issue. 

Styling changes should be done.

**Comment by joelpellucid** [comment]
Looking at this now

**Comment by joelpellucid** [comment]
Ok, the issue is that jquery.viewportchecker (for some reason) thinks it needs to add a "hidden" class to the content of hte modal sometime (it has to do with its parent being a certain class) -- so I added code that removes the hidden class each time the lightbox should be displayed, which has fixed the issue (at least for me).  Please let me know if it is still an issue for anyone else.
