### ISSUE TITLE
Add meta descriptions to all pages

### ISSUE THREAD

**Issue by ethompson-pellucid** [brettcrockett/brettcrockett.github.io#15]
https://moz.com/learn/seo/meta-description

Content will come from Jo.

**Comment by melinachastain** [comment]
Updated all descriptions except the ones for **Product - Demo**, **Product - Login**, and **About - Privacy**

**Comment by melinachastain** [comment]
Privacy policy meta data added

**Comment by ethompson-pellucid** [comment]
I'm not sure we need one for the remaining pages... What does Jo think?

**Comment by brettcrockett** [comment]
Nothing further required
