### ISSUE TITLE
Fix nav bar responsiveness

### ISSUE THREAD

**Issue by ethompson-pellucid** [brettcrockett/brettcrockett.github.io#18]
![screen shot 2016-08-10 at 1 42 33 pm](https://cloud.githubusercontent.com/assets/5314280/17568289/5a7cc60c-5f00-11e6-9cce-f945882c930a.png)

**Comment by ethompson-pellucid** [comment]
I'm OK with this looking like the mobirise menu (see below). I'm having a hard time finding out what happened here. @joelpellucid - Is this something you could look into tomorrow?

**Ours**
![screen shot 2016-08-10 at 5 05 08 pm](https://cloud.githubusercontent.com/assets/5314280/17574253/e18a0a44-5f1c-11e6-9544-ac1183ff21fe.png)

**Mobirise default**
![screen shot 2016-08-10 at 5 05 17 pm](https://cloud.githubusercontent.com/assets/5314280/17574252/e1883fb6-5f1c-11e6-8d97-32a0486b8a5b.png)

**Comment by melinachastain** [comment]
Should we break out the nav link to "Product" into "Overview" and "Features", as well as "Industries" into "Investment bankers" and "Strategic advisors"? Right now, once the secondary nav is hidden on mobile, I have to scroll to the footer to access these pages.

**Comment by ethompson-pellucid** [comment]
@melinachastain Yes - I added that here.

**Comment by melinachastain** [comment]
Nav bar now responsive on mobile

![screen shot 2016-08-12 at 4 29 56 pm](https://cloud.githubusercontent.com/assets/9119094/17638821/2b07ff76-60aa-11e6-902e-2408d7f0fa61.png)
