### ISSUE TITLE
Add arrows in between steps in How Pellucid Works section

### ISSUE THREAD

**Issue by melinachastain** [brettcrockett/brettcrockett.github.io#19]

**Comment by melinachastain** [comment]
arrow.png image is in assets > images

**Comment by brettcrockett** [comment]
@melinachastain The image for 'Connect Pellucid to your preferred data provider' is not as wide as the subsequent images, so it throws off the alignment quite a bit. Also, the arrows need to be resized / stylized appropriately. Are you able to amend?

**Comment by melinachastain** [comment]
@brettcrockett Yep. I'll look into this now

**Comment by melinachastain** [comment]
I resized the arrows and fixed the padding but there is something weird happening above 1200px (this is the break point) where it's adding extra padding just on the left hand arrows. Would you ming taking a look @joelpellucid ? 
![screen shot 2016-08-12 at 2 07 14 pm](https://cloud.githubusercontent.com/assets/9119094/17635722/454dc6ae-6096-11e6-854d-37fcc61a36a0.png)

**Comment by melinachastain** [comment]
Just found a fix.
