### ISSUE TITLE
Demo request form

### ISSUE THREAD

**Issue by ethompson-pellucid** [brettcrockett/brettcrockett.github.io#2]
Is there a central location where this form can be hosted? Or does this code need to be embedded for every link instance?

![screen shot 2016-08-09 at 9 15 33 am](https://cloud.githubusercontent.com/assets/5314280/17521790/e50b8654-5e11-11e6-94e0-ae0476a585d3.png)

**Comment by brettcrockett** [comment]
Still redundantly coded, but now working in commit 03200e5db2e9ea73fc47050547aa1b2171ac3319

**Comment by ethompson-pellucid** [comment]
Should I be getting this after submitting? https://formspree.io/brett.crockett@pellucid.com

**Comment by brettcrockett** [comment]
Use the live version, not the local version.


Brett

+1 720 336 5150  Direct
+1 720 278 5808  Cell

**Comment by ethompson-pellucid** [comment]
Will do. Heads up- I'm making some changes to the placeholder text.

**Comment by brettcrockett** [comment]
Yup, go for it. I took some artistic liberty versus what was in the
spreadsheet.


Brett

+1 720 336 5150  Direct
+1 720 278 5808  Cell
