### ISSUE TITLE
Leadership team section responsiveness

### ISSUE THREAD

**Issue by melinachastain** [brettcrockett/brettcrockett.github.io#20]

**Comment by melinachastain** [comment]
I can start working on this now

**Comment by ethompson-pellucid** [comment]
Brett - I'm going to attempt to restructure these so the team photos are background images. Hopefully allowing easier css repositioning for responsive views.

**Comment by brettcrockett** [comment]
OK, sounds sensible.


Brett

+1 720 336 5150  Direct
+1 720 278 5808  Cell

**Comment by ethompson-pellucid** [comment]
Done! and it is glorious...
