### ISSUE TITLE
Add alert copy to login modal

### ISSUE THREAD

**Issue by ethompson-pellucid** [brettcrockett/brettcrockett.github.io#22]
@joelpellucid - Do you know how we can add in this copy?
Mock up:
![screen shot 2016-08-10 at 4 30 33 pm](https://cloud.githubusercontent.com/assets/5314280/17573491/e20c9770-5f17-11e6-8643-cf3488e2af4d.png)

Current:
![screen shot 2016-08-10 at 4 30 50 pm](https://cloud.githubusercontent.com/assets/5314280/17573492/e3a4f97e-5f17-11e6-8d7a-53336e3103ab.png)

**Comment by joelpellucid** [comment]
doh, yep i'll get that in by tomorrow AM.

**Comment by ethompson-pellucid** [comment]
Thanks!

**Comment by joelpellucid** [comment]
This is done.
