### ISSUE TITLE
Increase height of demo modal

### ISSUE THREAD

**Issue by ethompson-pellucid** [brettcrockett/brettcrockett.github.io#26]
Trying to find where this lives...

![screen shot 2016-08-11 at 10 30 04 am](https://cloud.githubusercontent.com/assets/5314280/17596452/a21ab4ac-5fae-11e6-802a-c499e24225a5.png)

**Comment by brettcrockett** [comment]
I can't find this either... @joelpellucid could you help please?

**Comment by joelpellucid** [comment]
Doing this now.

**Comment by joelpellucid** [comment]
Added code to make it 800px tall.

**Comment by ethompson-pellucid** [comment]
That should help, thanks. Is it possible to make it based on the height of the viewport? I.e. 95%

**Comment by brettcrockett** [comment]
Where abouts is this specified? One of the style sheets?


Brett

+1 720 336 5150  Direct
+1 720 278 5808  Cell

**Comment by joelpellucid** [comment]
Lines 1003-1005 in style.css:
`.fancybox-inner {
  height: 800px !important;
}`

make the change.

**Comment by joelpellucid** [comment]
although that made the login modal 800 px :) so i'll fix that

**Comment by joelpellucid** [comment]
unfortunately, we can't do a css solution that fixes it for all demo modals, we can do a css solution for all fancybox modals or none at all, and since the login and demo modals are different heights, setting one breaks the other.

**Comment by brettcrockett** [comment]
So we would have to make, say, fancybox1 (for the login) and fancybox2 (for
the demo)?


Brett

+1 720 336 5150  Direct
+1 720 278 5808  Cell

**Comment by joelpellucid** [comment]
yes, exactly.
