### ISSUE TITLE
Responsiveness: (Careers) Replace team bubble photo with differently oriented version on mobile

### ISSUE THREAD

**Issue by melinachastain** [brettcrockett/brettcrockett.github.io#32]
![screen shot 2016-08-11 at 11 07 13 am](https://cloud.githubusercontent.com/assets/9119094/17597622/e3c7950a-5fb3-11e6-8ba5-a9897cf8bdd7.png)

**Comment by melinachastain** [comment]
@ethompson-pellucid I couldn't figure out this method without breaking it. Would you mind looking into this? The replacement image is in the assets folder as **pellucid-team-bubble-vertical.png**

**Comment by ethompson-pellucid** [comment]
Done. Still some spacing issues but let's roll that into #30
