### ISSUE TITLE
Add Salesfusion code to all forms

### ISSUE THREAD

**Issue by melinachastain** [brettcrockett/brettcrockett.github.io#33]

**Comment by brettcrockett** [comment]
<META HTTP-EQUIV="Content-type" CONTENT="text/html; charset=UTF-8">
<form action="http://emails.pellucid.com/RESTPostForm.aspx" method="POST">

<input type=hidden name="Customer" value="ch000096858eArad">
<input type=hidden name="cke" value="1">
<input type=hidden name="ownerid" value="1">
<input type=hidden name="overwrite" value="0">
<input type=hidden name="DialogID" value="30">
<input type=hidden name="PushExternal" value="1">
<input type=hidden name="rurl" value="https://brettcrockett.github.io/thankyoudemo">

<label for="Name">Name</label><input  id="Name" maxlength="40" name="Name" size="20" type="text" /><br>

<label for="Company">Company</label><input  id="Company" maxlength="40" name="Company" size="20" type="text" /><br>

<label for="Email">Email</label><input  id="Email" maxlength="40" name="Email" size="20" type="text" /><br>

<label for="Title">Title</label><input  id="Title" maxlength="40" name="Title" size="20" type="text" /><br>

<label for="Phone">Phone</label><input  id="Phone" maxlength="40" name="Phone" size="20" type="text" /><br>

<label for="Industry">Industry</label><input  id="Industry" maxlength="40" name="Industry" size="20" type="text" /><br>

<input type="submit" name="submit">

</form>

**Comment by brettcrockett** [comment]
This requires the ability to have two 'form posts' with on 'submit' button click, e.g.
> <form action="https://formspree.io/brett.crockett@pellucid.com" method="post">
> <form action="https://salesfusion.something..." method="post">

**Comment by brettcrockett** [comment]
Done. Tested. Seems to be working as intended.
