### ISSUE TITLE
Lightbox issue

### ISSUE THREAD

**Issue by ethompson-pellucid** [brettcrockett/brettcrockett.github.io#42]
There is a type of wrapped around the carousel that is causing problems with closing the lightbox by clicking into the "negative" space.

For example, if you click to the right or left of the image (red), it does not close. I thought I was clever and made the background transparent, but that doesn't do anything when you try to click to close.

![screen shot 2016-08-11 at 4 40 59 pm](https://cloud.githubusercontent.com/assets/5314280/17607438/f729ddd6-5fe2-11e6-8ee5-b40d4f633c46.png)

All of the changes I made to the lightbox were done in the Pellucid css file.

**Comment by brettcrockett** [comment]
Can we close this issue now?

**Comment by ethompson-pellucid** [comment]
We're probably good here. I haven't tested this as vigorously recently, but I'm not having any problems with it now.

**Comment by ethompson-pellucid** [comment]
Sorry, in my last comment I was thinking this was #12

This was definitely resolved by Joel.
