### ISSUE TITLE
Required fields on Demo request form

### ISSUE THREAD

**Issue by melinachastain** [brettcrockett/brettcrockett.github.io#43]
Can we make email address, name, and company require fields?

**Comment by ethompson-pellucid** [comment]
To clarity, any field that isn't labeled as (optional) should be required.

**Comment by brettcrockett** [comment]
@joelpellucid Is this just a simple JavaScipt form validation that you could easily implement?

**Comment by joelpellucid** [comment]
Looking at this now

**Comment by ethompson-pellucid** [comment]
Thanks Joel! Per Jo, could we please make the error message read "Mandatory missing information highlighted in red" See mock up below.
![screen shot 2016-08-15 at 9 23 48 am](https://cloud.githubusercontent.com/assets/5314280/17669233/1465b32c-62ca-11e6-9fea-1d17bab745d5.png)

**Comment by brettcrockett** [comment]
Is this "Mandatory missing information highlighted in red" language all that is required here?

**Comment by ethompson-pellucid** [comment]
Yes

**Comment by joelpellucid** [comment]
I will make another sweep through today and that guy is at top of mind

**Comment by brettcrockett** [comment]
I've already updated this. Ticket closed.
