### ISSUE TITLE
Make appropriate fields required on contact us form

### ISSUE THREAD

**Issue by melinachastain** [brettcrockett/brettcrockett.github.io#45]
Name, email, and message?

**Comment by brettcrockett** [comment]
@joelpellucid Is this just a simple JavaScipt form validation that you could easily implement? Same as #43

**Comment by joelpellucid** [comment]
Yes I believe so.  Doing this now.

**Comment by brettcrockett** [comment]
'Company' is listed as optional, but the form treats it as mandatory

**Comment by brettcrockett** [comment]
@ethompson-pellucid or @melinachastain The "Mandatory missing information highlighted in red." text is too long/large and breaks to a new line on https://www.pellucid.com/about-contact

**Comment by ethompson-pellucid** [comment]
Thanks, I'll set it to display on it's own line with css.

**Comment by ethompson-pellucid** [comment]
Fixed.

Closing this since I opened a new issue for #62
