### ISSUE TITLE
Mobile nav appears while I resize browser without having opened it

### ISSUE THREAD

**Issue by ethompson-pellucid** [brettcrockett/brettcrockett.github.io#50]
@joelpellucid - I know you're updating this now, but wanted to let you know this happened...

![screen shot 2016-08-12 at 1 48 29 pm](https://cloud.githubusercontent.com/assets/5314280/17635251/8bc84c06-6093-11e6-9b72-3261929f757b.png)

**Comment by ethompson-pellucid** [comment]
It occurs exactly at the 767px break point

**Comment by joelpellucid** [comment]
fixed.
