### ISSUE TITLE
Formspree error

### ISSUE THREAD

**Issue by ethompson-pellucid** [brettcrockett/brettcrockett.github.io#56]
I just tried submitting the contact form with "Support" selected and received this...

![screen shot 2016-08-15 at 1 26 25 pm](https://cloud.githubusercontent.com/assets/5314280/17676475/f66d8332-62eb-11e6-9c7a-cf87dd296b58.png)

**Comment by ethompson-pellucid** [comment]
Question is, do we want this to happen? Seems odd to have validation on top of validation...

**Comment by brettcrockett** [comment]
The server validates the email. Our JavaScript doesn't. If we can get our JavaScript to validate the format of the email address, this won't happen. @joelpellucid Is it easy to add email format validation?

**Comment by joelpellucid** [comment]
This is fixed, the form is not able to submit now unless the email field has a valid email

**Comment by ethompson-pellucid** [comment]
@joelpellucid - Don't hate me, but can we add error/help text under the field to explain why it was rejected?

**Comment by ethompson-pellucid** [comment]
"Please provide a valid email address"

**Comment by brettcrockett** [comment]
Appears to be resolved now
