### ISSUE TITLE
Scroll issue on iphone - Demo form

### ISSUE THREAD

**Issue by melinachastain** [brettcrockett/brettcrockett.github.io#59]
Iphone scrolls the entire page instead of within the modal. Once it hits the top of the page then I am able to scroll within the module.

![image1](https://cloud.githubusercontent.com/assets/9119094/17710227/98bcbe6a-63a9-11e6-8416-7cee0b078749.PNG)

![image2 1](https://cloud.githubusercontent.com/assets/9119094/17710231/9b91db8e-63a9-11e6-883b-eecec8298400.PNG)

**Comment by brettcrockett** [comment]
Form removed
