### ISSUE TITLE
Salesfusion website tracking code

### ISSUE THREAD

**Issue by melinachastain** [brettcrockett/brettcrockett.github.io#60]
@brettcrockett Can we inject this code into the header or footer where the Google Analytics tracking code is? It's for Salesfusion so when we collect and cookie leads we can see their activity on the site.

<script type="text/javascript">
__sf_config = {
customer_id: 96858,
host: 'emails.pellucid.com',
ip_privacy: 0,
subsite: 'eadcc0ac-de2d-4c41-9288-dc481cf72eef',

__img_path: "/web-next.gif?"
};

(function() {
var s = function() {
var e, t;
var n = 10;
var r = 0;
e = document.createElement("script");
e.type = "text/javascript";
e.async = true;
e.src = "//" + __sf_config.host + "/js/frs-next.js";
t = document.getElementsByTagName("script")[0];
t.parentNode.insertBefore(e, t);
var i = function() {
if (r < n) {
r++;
if (typeof frt !== "undefined") {
frt(__sf_config);
} else {
setTimeout(function() { i(); }, 500);
}
}
};
i();
};
if (window.attachEvent) {
window.attachEvent("onload", s);
} else {
window.addEventListener("load", s, false);
}
})();
</script>

**Comment by melinachastain** [comment]
`<script type="text/javascript">
__sf_config = {
customer_id: 96858,
host: 'emails.pellucid.com',
ip_privacy: 0,
subsite: 'eadcc0ac-de2d-4c41-9288-dc481cf72eef',

__img_path: "/web-next.gif?"
};

(function() {
var s = function() {
var e, t;
var n = 10;
var r = 0;
e = document.createElement("script");
e.type = "text/javascript";
e.async = true;
e.src = "//" + __sf_config.host + "/js/frs-next.js";
t = document.getElementsByTagName("script")[0];
t.parentNode.insertBefore(e, t);
var i = function() {
if (r < n) {
r++;
if (typeof frt !== "undefined") {
frt(__sf_config);
} else {
setTimeout(function() { i(); }, 500);
}
}
};
i();
};
if (window.attachEvent) {
window.attachEvent("onload", s);
} else {
window.addEventListener("load", s, false);
}
})();
</script>`

**Comment by melinachastain** [comment]
<script type="text/javascript">
    __sf_config = {
    customer_id: 96858,
    host: 'emails.pellucid.com',
    ip_privacy: 0,
    subsite: 'eadcc0ac-de2d-4c41-9288-dc481cf72eef',

    __img_path: "/web-next.gif?"
    };

    (function() {
    var s = function() {
    var e, t;
    var n = 10;
    var r = 0;
    e = document.createElement("script");
    e.type = "text/javascript";
    e.async = true;
    e.src = "//" + __sf_config.host + "/js/frs-next.js";
    t = document.getElementsByTagName("script")[0];
    t.parentNode.insertBefore(e, t);
    var i = function() {
    if (r < n) {
    r++;
    if (typeof frt !== "undefined") {
    frt(__sf_config);
    } else {
    setTimeout(function() { i(); }, 500);
    }
    }
    };
    i();
    };
    if (window.attachEvent) {
    window.attachEvent("onload", s);
    } else {
    window.addEventListener("load", s, false);
    }
    })();
    </script>

**Comment by brettcrockett** [comment]
Done
