### ISSUE TITLE
Careers form

### ISSUE THREAD

**Issue by ethompson-pellucid** [brettcrockett/brettcrockett.github.io#66]
> Landing pages:  I think we should have more specific landing pages for both the career and partnerships forms rather than taking us to the contact us page.  My general thought is that we also need to get better at landing pages if we are going to run any paid marketing campaign

We should make this it's own page like we did for Request a demo. Need to follow up with Jo to determine needed fields.

**Comment by ethompson-pellucid** [comment]
**Name**
**Email**
**Phone (optional)**
**Resume (attachment)**
**Website or portfolio** 
**Message**

**Comment by brettcrockett** [comment]
Done. @ethompson-pellucid Did you want to (1) make any stylist amendments needed, and (2) check that Jo is happy with the content and then I'll redirect the link to here? http://www.pellucid.com/request-career

Note that I dropped off the resume attachment; I would prefer to just look at people's LinkedIn profiles
