### ISSUE TITLE
Partnerships form

### ISSUE THREAD

**Issue by ethompson-pellucid** [brettcrockett/brettcrockett.github.io#67]
> Landing pages:  I think we should have more specific landing pages for both the career and partnerships forms rather than taking us to the contact us page.  My general thought is that we also need to get better at landing pages if we are going to run any paid marketing campaign

We should make this it's own page like we did for Request a demo. Need to follow up with Jo to determine needed fields.

**Comment by ethompson-pellucid** [comment]
**Name**				
**Email**				
**Phone (optional)**				
**Company**				
**Partnership type:**
- Data provider
- Educator
- Content creator
- KPO

**Message**

**Comment by brettcrockett** [comment]
Done. @ethompson-pellucid Did you want to (1) make any stylist amendments needed, and (2) check that Jo is happy with the content and then I'll redirect the link to here? http://www.pellucid.com/request-partnership

**Comment by ethompson-pellucid** [comment]
Should we put this form directly on this page?
http://www.pellucid.com/about-partnerships

Also, let's create a custom thank you page for this guy.

**Comment by brettcrockett** [comment]
For consistencies sake, I would argue no.

Happy to create a custom page; did you want to bug Jo for text, or shall I?

**Comment by ethompson-pellucid** [comment]
Hmm, OK.

I'll let you bug her :) Not sure she wants text, but please have her review.

**Comment by ethompson-pellucid** [comment]
Ah, sorry, we do need text for the custom thank you page.
