### ISSUE TITLE
Fix spacing on login form- error causes submit to go partially out of view

### ISSUE THREAD

**Issue by ethompson-pellucid** [brettcrockett/brettcrockett.github.io#69]
<img width="686" alt="screen shot 2016-08-19 at 8 21 29 am" src="https://cloud.githubusercontent.com/assets/5314280/17812844/0121e4ce-65e6-11e6-9370-a2717d1b29fb.png">

**Comment by mlms13** [comment]
I'm pretty confident that I fixed this when I made changes a couple weeks ago. The button still shifts a little, but it doesn't cause any scrolling.
